### ISSUE TITLE
Risk of overflow in add_mod

### ISSUE THREAD

**Issue by deepink-mas** [andreacorbellini/rust-circular-buffer#1]
Function add_mod does not seem to live up to its documentation regarding "without risk of overflows if ...". Perhaps this case is not relevant, but then this comment should be less unequivocal.
```
/// Returns `(x + y) % m` without risk of overflows if `x + y` cannot fit in `usize`.
const fn add_mod(x: usize, y: usize, m: usize) -> usize {
    let (z, overflow) = x.overflowing_add(y);
    z % m + (overflow as usize) * (usize::MAX % m + 1)
}

#[test]
fn t() {
    assert_eq!(0, add_mod(usize::MAX, usize::MAX, usize::MAX));
}
```

> thread 't' panicked at 'assertion failed: `(left == right)`
>   left: `0`,
>  right: `18446744073709551615`', src/lib.rs:8:5

**Comment by andreacorbellini** [comment]
Hi, the "overflow" that the rustdoc talks about is an integer overflow. You can see that the code you pasted does not cause overflow because the panic message you get is "assertion failed", not "attempt to add with overflow".

This function, which is not public, implicitly assumes that `x` is strictly less than `m`, and that `y` is less than or equal to `m`. Therefore the reason why you're getting `usize::MAX` is that the `x` that you are passing is breaking the first assumption. None of the code in circular-buffer ever passes an `x` equal to `m`, so this is not a bug.

However I can see how this can cause confusion. I'm going to change `add_mod()` so that `x` *may* be equal to `m`. This change is not necessary, as there is no bug, but I'm doing it anyway to clear possible confusion that may arise in the future. I'll also document the assumptions for this function.

**Comment by andreacorbellini** [comment]
Thanks for your feedback, feel free to report future issues if you find them.

**Comment by deepink-mas** [comment]
Thanks for the thorough fix.
