### ISSUE TITLE
Is it working as intended?

### ISSUE THREAD

**Issue by q2p** [andreacorbellini/rust-circular-buffer#10]
Taking a few glimpses at the source code I found a few spots that made a little confused.

Here for example:
https://github.com/andreacorbellini/rust-circular-buffer/blob/8d4b63378d443bcbf1e955554911b6d90579892c/src/lib.rs#L1479-L1513

Why does it say that `truncate_front(0)` is equivalent to `clear()`? I assume it is supposed to clear the buffer, but it only does an early return, without changing any cursors or dropping any values.

It also says "The `start` of the buffer is shrunk before dropping, so no value will be dropped twice in case of panics."
When in reality the `start` is changed after calling `self.drop_range`.

Are you planning on actively maintaining this crate or is it just a small side-project?

**Comment by andreacorbellini** [comment]
This crate is actively maintained. I published 5 releases within the last 6
months. I'm not sure why anyone would think it's not actively maintained.

About your specific concerns: clear() and
truncate_front(0)/truncate_back(0) are semantically equivalent because both
remove all items from the buffer. Not sure why you claim it does an "early
return". If you would mind to share some code that shows an actual issue
I'd be happy to look at it and get it fixed.

Regarding the changing of start/len before calling drop_range: you may have
a valid point here. This is likely the result of an internal refactoring
that accidentally swapped the order of operations. I'll get it fixed when I
have a chance.

**Comment by q2p** [comment]
My bad, I confused `N` and `len`, so I thought it's doing an early return.
